from datetime import date
from typing import Optional

import pytest

from ancv.visualization.themes import Theme


@pytest.mark.parametrize(
    ["start", "end", "fmt", "sep", "ongoing", "expected", "collapse"],
    [
        (
            None,
            None,
            "",
            "",
            "",
            "",
            False,
        ),
        (
            None,
            None,
            "%Y-%m-%d",
            "",
            "",
            "",
            False,
        ),
        (
            None,
            None,
            "%Y-%m-%d",
            "-",
            "",
            "",
            False,
        ),
        (
            None,
            None,
            "%Y-%m-%d",
            "-",
            "present",
            "",
            False,
        ),
        (
            date(2020, 1, 1),
            None,
            "%Y-%m-%d",
            "",
            "",
            "2020-01-01  ",
            False,
        ),
        (
            date(2020, 1, 10),
            None,
            "%Y-%m-%d",
            "",
            "",
            "2020-01-10  ",
            False,
        ),
        (
            date(2020, 1, 1),
            None,
            "%Y-%m-%d",
            "-",
            "",
            "2020-01-01 - ",
            False,
        ),
        (
            date(2020, 1, 1),
            None,
            "%Y-%m-%d",
            "-",
            "present",
            "2020-01-01 - present",
            False,
        ),
        (
            date(2020, 1, 1),
            None,
            "%Y-%m-%d",
            "...",
            "present",
            "2020-01-01 ... present",
            False,
        ),
        (
            date(2020, 1, 1),
            date(2020, 1, 2),
            "%Y-%m-%d",
            "",
            "",
            "2020-01-01  2020-01-02",
            False,
        ),
        (
            date(2020, 1, 1),
            date(2020, 1, 2),
            "%Y-%m-%d",
            "-",
            "",
            "2020-01-01 - 2020-01-02",
            False,
        ),
        (
            None,
            date(2020, 1, 2),
            "%Y-%m-%d",
            "",
            "",
            " 2020-01-02",
            False,
        ),
        (
            None,
            date(2020, 1, 2),
            "%Y-%m-%d",
            "-",
            "",
            "- 2020-01-02",
            False,
        ),
        (
            None,
            date(2020, 1, 2),
            "%Y-%m-%d",
            "-",
            "present",
            "- 2020-01-02",
            False,
        ),
        (
            date(2020, 1, 1),
            date(2020, 1, 2),
            "%Y-%m",
            "",
            "",
            "2020-01",
            True,
        ),
        (
            date(2020, 1, 1),
            date(2020, 1, 2),
            "%Y-%m",
            "-",
            "",
            "2020-01",
            True,
        ),
        (
            date(2020, 1, 1),
            date(2020, 1, 31),
            "%Y-%m",
            "-",
            "",
            "2020-01",
            True,
        ),
        (
            date(2020, 1, 1),
            date(2020, 2, 1),
            "%Y-%m",
            "-",
            "",
            "2020-01 - 2020-02",
            True,
        ),
        (
            date(2020, 12, 1),
            date(2020, 12, 31),
            "%B %Y",
            "-",
            "",
            "December 2020",
            True,
        ),
        (
            date(2020, 1, 1),
            date(2020, 2, 1),
            "%B %Y",
            "-",
            "",
            "January 2020 - February 2020",
            True,
        ),
    ],
)
def test_default_date_range(
    start: Optional[date],
    end: Optional[date],
    fmt: str,
    sep: str,
    ongoing: str,
    expected: str,
    collapse: bool,
) -> None:
    assert Theme.date_range(start, end, fmt, sep, ongoing, collapse) == expected
