repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: check-import-sorting
        name: Check import sorting
        language: system
        entry: make isortcheck
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: check-formatting
        name: Check formatting
        language: system
        entry: make formatcheck
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: run-typecheck
        name: Run typecheck
        language: system
        entry: make typecheck
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        language: system
        entry: make test
        stages:
          - "commit"
          - "push"
        types:
          - file
          - python
  - repo: local
    hooks:
      - id: build-image
        name: Build image
        language: system
        entry: make image
        stages:
          - "push"
