name: ancv
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
functions:
  - name: api
    github:
      branch: do
      deploy_on_push: true
      repo: alexpovel/ancv
    routes:
      - path: /api
    source_dir: .do/functions/
    envs:
      - key: "GH_REQUESTER"
        type: "SECRET"
        scope: "RUN_TIME"
      - key: "GH_TOKEN"
        type: "SECRET"
        scope: "RUN_TIME"
      - key: "REPO_URL"
        scope: "RUN_TIME"
domains:
  - domain: "ancv.io"
    type: "PRIMARY"
