volumes:
  proxy_data:
  proxy_config:


services:
  proxy:
    image: caddy:2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - proxy_data:/data # Certs, keys etc.
      - proxy_config:/config # Configuration files
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  ancv:
    image: ghcr.io/alexpovel/ancv:main
    volumes:
      - ./resume.json:/resume.json:ro
    ports:
      - 8080:8080
    command:
      [
        "serve",
        "file",
        "/resume.json",
        "--port",
        "8080"
      ]
    restart: unless-stopped
