# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests

    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.2.0b3

      - name: Set up Python environment
        run: poetry install

      - name: Run tests
        run: make test

      - name: Run type checks
        run: make typecheck

      - name: Check code formatting
        run: make formatcheck

      - name: Check imports formatting
        run: make isortcheck

  release-please:
    name: Execute release chores

    runs-on: ubuntu-latest
    needs: tests

    outputs:
      created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: ancv

  publish:
    name: Publish to PyPI

    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.created }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.2.0b3

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  build-and-push-image:
    name: Build Docker image and push to GitHub Container Registry

    runs-on: ubuntu-latest
    needs: publish

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
